### ISSUE TITLE
Remove Maven variables from all configuration of built components

### ISSUE THREAD

**Issue by morungos** [cBioPortal/icebox#25]
We've had a long-running issue with the way Maven variables are baked into the war file. This means, to all intents and purposes, each user is compiling and building their own version of cBioPortal -- there is no standardization possible. 

There are good historical reasons for this. At the time, it was the easiest way to customize. But newer techniques have emerged, such as [war overlays](http://maven.apache.org/plugins/maven-war-plugin/overlays.html) that make it possible to override local values without affecting the integrity of a standard core component. 

I'd propose: removing, as far as humanly possible, all Maven variable templating for the web application except where it is used for code factoring and/or testing. Putting DB settings into test files is fine, but core should not depend on them. Instead, Java properties and/or environment variables should inject key settings. JNDI is another option. Any approach that moves settings to runtime should be fair game. 

As a consequence, Maven should no longer depend on `PORTAL_HOME`. 

Directly related issues:
- https://github.com/cBioPortal/cbioportal/issues/938
- https://github.com/cBioPortal/cbioportal/issues/1088
- https://github.com/cBioPortal/cbioportal/issues/1169

**Comment by fedde-s** [comment]
I believe that this has been largely addressed in https://github.com/cBioPortal/cbioportal/pull/4787 and its followups, and actively used in the [Docker setup](https://github.com/cBioPortal/cbioportal/pull/6063/). A few remaining points of confusion are listed in or linked from https://github.com/cBioPortal/cbioportal/issues/6110.

**Comment by fedde-s** [comment]
There is still [some logic that may cause confusion](https://github.com/cBioPortal/cbioportal/issues/4832#issuecomment-492228445), but that should be covered by the other issue reports I linked.

**Comment by fedde-s** [comment]
Does anyone think that this should _not_ be closed yet?

**Comment by fedde-s** [comment]
Apparently not.
