### ISSUE TITLE
Unknown cBioPortal version in validation report

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/icebox#55]
Command line output:
`INFO: -: Running validation from cBioPortal version 0-unknown-version-SNAPSHOT`

In validation report:
<img width="977" alt="screenshot 2019-01-17 at 15 31 17" src="https://user-images.githubusercontent.com/9624990/51325373-1229d680-1a6d-11e9-8f8d-916e211d5b6f.png">

**Comment by jjgao** [comment]
@Sjoerd-van-Hagen I moved this to icebox. Please feel free to move it back once you work on it.

**Comment by Sjoerd-van-Hagen** [comment]
@SRodenburg if you have time left you can have a look at this.

**Comment by Sjoerd-van-Hagen** [comment]
@SRodenburg can this be closed?
